[
    {
        "question": "The trailer hand valve senses air pressure to the trailer brake system through?",
        "answer": "Control line (service line)\n"
    },
    {
        "question": "What is the main purpose of a hand valve?",
        "answer": "To control independently the amount of air application to be directed to the trailer brakes."
    },
    {
        "question": "In a dual circuit system, the primary circuit supplies air to?",
        "answer": "The rear brake chambers."
    },
    {
        "question": "On most dual air brake system, the primary air reservoir, supply air to the?",
        "answer": "Rear brake chambers."
    },
    {
        "question": "The dual foot valve is supplied with air from?",
        "answer": "Primary and secondary reservoir."
    },
    {
        "question": "What is the main purpose of air compressor?",
        "answer": "The source of energy for the air brake system."
    },
    {
        "question": "At what pressure should the low-pressure warning device system activate?",
        "answer": "60 PSI."
    },
    {
        "question": "Which are the common measures of air pressure?",
        "answer": "Pound per square inch and kilo pascal."
    },
    {
        "question": "Two-way check valve?",
        "answer": "Releases the highest pressure.\n"
    },
    {
        "question": "If the trailer brakes away, the purpose of the tractor protection valve is to?",
        "answer": "To prevent loss of air from the tractor."
    },
    {
        "question": "A tug test on the trailer brakes should be done?",
        "answer": "With the hand valve applied."
    },
    {
        "question": "How often should the supply reservoir be drained?",
        "answer": "Daily."
    },
    {
        "question": "If the front axle limiting value is the slippery road position and the foot is depressed to make a brake application of 30 PSI. How much pressure will be applied in the front brake chambers?",
        "answer": "15 PSI.\n"
    },
    {
        "question": "What is meant by braking distance?",
        "answer": "The actual distance the vehicle travels after the brake is applied until the vehicle stop.\n"
    },
    {
        "question": "What is the main purpose of an emergency release tank?",
        "answer": "Supply air to release and re apply the parking brakes if main reservoir air is lost."
    },
    {
        "question": "When checking slack adjusters push rod travel by hand or pry-bar travel should not exceed?",
        "answer": "¾ inch – 0.75 inch."
    },
    {
        "question": "If the front axle limiting valve is in the slippery road position and when makes a brakes application, how much percent goes in the front brake chamber?",
        "answer": "50 percent."
    },
    {
        "question": "What are the five basic components of an air brake system?",
        "answer": "Compressor, governor, air lines, foot valve, foundation brakes and reservoir.\n"
    },
    {
        "question": "In a dual circuit air system what valve is used to protect the primary circuit from the air loss in the secondary circuit?",
        "answer": "Two-way check valve."
    },
    {
        "question": "Why are air brakes rather than hydraulic brakes, used on heavy commercial vehicles?",
        "answer": "Air brakes are more powerful than hydraulic braking system."
    },
    {
        "question": "In which direction should the adjusting nut (bolt) be turned to tighten the brakes?",
        "answer": "Make the S-Cam shaft rotate in the same direction as brake application."
    },
    {
        "question": "When supply line broken, tractor pressure should not drain below?",
        "answer": "45 PSI to 20 PSI."
    },
    {
        "question": "What is the maximum pressure available for a full brake application at any given time?",
        "answer": "Pressure in the main reservoir (Reservoir pressure)."
    },
    {
        "question": "How often should the reservoirs be drained?",
        "answer": "Daily or more often in extreme conditions."
    },
    {
        "question": "Excessive accumulation of oil in the reservoirs could indicate?",
        "answer": "Compressor piston rings worn."
    },
    {
        "question": "On a tractor and double trailer, what is the maximum air lost during one minute.",
        "answer": "6 PSI.\n"
    },
    {
        "question": "What does the term foundation break refer to?",
        "answer": "The brake components at each of the wheel."
    },
    {
        "question": "What are the other foundation brakes found on air brake vehicles?",
        "answer": "Wedge brakes, Air disc brakes, Air over hydraulics brakes.\n"
    },
    {
        "question": "What is the main purpose of the air compressor?",
        "answer": "The source of energy for the air brake system.\n"
    },
    {
        "question": "The heat generated by the brakes?",
        "answer": "Absorbed by the brake drums and linings and dissipated into the atmosphere."
    },
    {
        "question": "What are three functions of the slack adjuster?",
        "answer": "Connection between Push Rod and S-Cam, brake adjustment, mechanical lever.\n"
    },
    {
        "question": "What does the \"feel\" of an air operated foot valve differ from hydraulic pedal?",
        "answer": "Air treaties are spring loaded."
    },
    {
        "question": "Spring brake emergency release systems are used to?",
        "answer": "Release the spring brakes if a disabled vehicle needs to be moved to a safe parking area."
    },
    {
        "question": "What is the final factor that will determine if the vehicle will move?",
        "answer": "The amount of traction."
    },
    {
        "question": "Most trailer’s reservoir is filled with air through the?",
        "answer": "Relay emergency valve."
    },
    {
        "question": "The low air pressure warning device activate at approximately?",
        "answer": "60 PSI"
    },
    {
        "question": "50 P.S.I to 90 P.S.I pressure should built in?",
        "answer": "Three minutes.\n"
    },
    {
        "question": "In most trailers the reservoir is filled with air through the?",
        "answer": "Relay emergency valve."
    },
    {
        "question": "Why should the glad hands be protected when not in use?",
        "answer": "To keep them clean of dirt and moisture.\n"
    },
    {
        "question": "If 40 PSI is excreted against a diaphragm of 30 square inch area, what is the total force which could be excreted?",
        "answer": "1200 lb. of force."
    },
    {
        "question": "The main advantage of a dual air brake system is that it?",
        "answer": "Prevent total brake failure."
    },
    {
        "question": "In the interest of safety, who ensures the braking system is operational?",
        "answer": "The Driver.\n"
    },
    {
        "question": "How is heat that is generated by the air brakes dissipated?",
        "answer": "Absorbed by the brake drums and dissipated into the atmosphere."
    },
    {
        "question": "If the foot valve and the hand valve are operated at the same time, the trailer application pressure will be?",
        "answer": "The highest pressure being applied by hand valve or foot valve."
    },
    {
        "question": "If the ABS light comes on while driving you will have?",
        "answer": "Full function brakes.\n"
    },
    {
        "question": "What will occur if the supply line ruptures?",
        "answer": "The trailer brakes will dynamite immediately. *"
    },
    {
        "question": "The spring brake modulator valve?",
        "answer": "Allow the spring brake to activate in the event of primary system fail.\n"
    },
    {
        "question": "When u makes a full brake application push rod travels in automatic slack adjuster should not exceed,",
        "answer": "Not more than two inches."
    },
    {
        "question": "To control speed on a downgrade, it is good practice to?",
        "answer": "Select correct gear with small even brake application."
    },
    {
        "question": "In the interest of safety, the final responsibility to ensure that the braking?",
        "answer": "The driver."
    }
]